source $HOME/.zsh/config/variables.zsh
source $HOME/.zsh/config/aliases.zsh

plugins=(git)
source $ZSH/oh-my-zsh.sh
[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh


[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && { type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; } }
